name: Static Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run static checks
      run: uv run pre-commit run --all-files

